#!/bin/bash
gfortran -ggdb \
      fmods_2_2.f \
      unsat.f\
      indatet.f90 \
      ssubs_2_2.f \
      sutra_2_2.f \
      usubs_2_2.f \
      gversion.f90 \
      -o sutra_debug_gf
# comments: -g sometimes may be able to display line number properly,
# but if it does not, use -ggdb instead.

