
!  FUNCTION TO CALCULATE SURFACE RESISTANCE 
!   MSR=0, SYRFSIS=0
!   MSR=1, USING CAMILO(1986) FORMULAR
!   MSR=2, USING SUN (1982) FORMULAR
!   MSR=3, USING DAAMEN (1996) FORMULAR
!   MSR=4, USING VAN DER GRIEND (1994) FORMULAR
!   MSR=5, USING HYPERGEOMETRIC FUNCTIONS SEE PAGE 142 OF 
!          BLUEBOOK, 98(5)
!   MSR=6, USING APPROXIMATED EQUATION GIVEN BY PAPER 2, USING THE
!  POTENTIAL RESULT AT THE TOPMOST CELL
!   MSR=7, USING APPROXIMATED EQUATION GIVEN BY PAPER 2, BUT THE 
!  CONTRIBUTION OF VAPOR HAS BEEN CHANGED INTO PHYSICAL BASED METHOD

   DOUBLE PRECISION FUNCTION SURFRSIS(PP,POR,SW,MSR,KREG,TSK,YY)
   USE M_SURFR
   USE M_PARAMS
   USE M_SWCC
   IMPLICIT DOUBLE PRECISION (A-H,O-Z)
   COMMON /PARAMS/ COMPFL,COMPMA,DRWDU,CW,CS,RHOS,SIGMAW,SIGMAS, &
        RHOW0,URHOW0,VISC0,PRODF1,PRODS1,PRODF0,PRODS0,CHI1,CHI2 
!   COMMON /SURFR/ TAL,EC,ETR 
!   COMMON /AERORESIS/ RAVT,RAVS,SWRAT
!   PP --PORE WATER PRESSURE
!   TSK--TEMPERATURE
   IF (MSR.EQ.0) THEN
       SURFRSIS=0.D0
   ELSEIF(MSR.EQ.1)THEN
       SURFRSIS=-8.05D2+4.14D3*POR*(1-SW)
   ELSEIF(MSR.EQ.2)THEN
       SURFRSIS=3.5D0*SW**(-2.3D0)+33.5D0
   ELSEIF(MSR.EQ.3)THEN
       SURFRSIS=3.D10*(POR*(1-SW))**16.6D0
   ELSEIF(MSR.EQ.4)THEN
       SURFRSIS=10.D0*EXP(35.63D0*POR*(0.375D0-SW))
!  SEE PAGE 98(4) OF DERIVE BOOK 2003 FOR REFERENCE
!  METHOD 5  IS NOT SUGGESTED TO USE THIS MODEL 
!  AS IT IS A TRANSIENT STAGE OF PAPER2
   ELSEIF(MSR.EQ.5)THEN
! SURFACE RESISTANCE AFTER THE APPROXIMATION SEE PAGE 
   ELSEIF(MSR.EQ.6)THEN
!  CONVERT PORE WATER PRESSURE (NEGATIVE) [PP] INTO CAPLIIARY HEAD 
!    (M)
     PSIC=-PP/GVA/RHOW0
!    CHECKING THE SOIL CHARACTERISTIC PARAMETERS
     IF(KREG.EQ.3)THEN
       DLAM=DLAM3
       PSICB=PSICB3
     ELSEIF(KERG.EQ.4)THEN
       DLAM=DLAM4   
       PSICB=PSICB4   
     ENDIF
!    EVALUATING RS BY DIFFERENT PSIC VALUE
     IF (PSIC.LE.PSICB)THEN
       SURFRSIS=0.D0
     ELSEIF (PSIC.GT.PSICB)THEN
       ETI=ETR*DLOG(PSIC0/PSIC)/DLOG(PSIC0)
       ETRMS=1.D0-ETI
!      (E)FFECTIVE (S)ATURATION AFTER G FUNCTION
       SET=(PSICB/PSIC)**(DLAM*(1+EC))
!      POR*SET
       PORSE=POR*SET
!      PARAMETER IN THE HYPERGEOMETRIC
       C=(1/PORSE-1/SQRT(PORSE))/2.D0/TAL
!      EXPECTANT VALUE OF R1 AT GIVEN MATRIC POTENTIAL 
!      (UNDER BROOKS&COREY)
!      SEE EQUATION (A1) OF PAPER 2
       R1EFF=-DLAM*ZETA/(DLAM+1)/PSIC
       RELKV=1/(1+C*R1EFF)*ETRMS+ETI
       SURFRSIS=TAL/DVA(TSK)/RELKV
     ENDIF
! SURFACE RESISTANCE AFTER THE APPROXIMATION SEE PAGE 229
   ELSEIF(MSR.EQ.7)THEN
!  CONVERT PORE WATER PRESSURE (NEGATIVE) [PP] INTO CAPLIIARY HEAD 
!    (M)
     PSIC=-PP/GVA/RHOW0
!    CHECKING THE SOIL CHARACTERISTIC PARAMETERS
     IF(KREG.EQ.3)THEN
       DLAM=DLAM3
       PSICB=PSICB3
     ELSEIF(KERG.EQ.4)THEN
       DLAM=DLAM4   
       PSICB=PSICB4   
     ENDIF
!    EVALUATING RS BY DIFFERENT PSIC VALUE
     IF (PSIC.LE.PSICB)THEN
       SURFRSIS=0.D0
     ELSEIF (PSIC.GT.PSICB)THEN
!      KVRV INDUCED BY VAPOR AT STAGE IV SEE PAGE 229
       ETI=COER*0.66D0*TAL*POR*DLOG(PSIC0)/(YY*DLOG(PSIC+PSIP))
!      (E)FFECTIVE (S)ATURATION AFTER G FUNCTION
       SET=(PSICB/PSIC)**(DLAM*(1+EC))
!      POR*SET
       PORSE=POR*SET
!      PARAMETER IN THE HYPERGEOMETRIC
       C=(1/PORSE-1/SQRT(PORSE))/2.D0/TAL
!      EXPECTANT VALUE OF R1 AT GIVEN MATRIC POTENTIAL 
!      (UNDER BROOKS&COREY)
!      SEE EQUATION (A1) OF PAPER 2
!      THE NEGATIVE SYMBOL IS THAT PSIC=-PSIM
       R1EFF=-DLAM*ZETA/(DLAM+1)/PSIC
       RELKV=1/(1+C*R1EFF)+(1-SW)*ETI
       SURFRSIS=TAL/DVA(TSK)/RELKV
     ENDIF
   ELSEIF(MSR.EQ.8)THEN
!  CONVERT PORE WATER PRESSURE (NEGATIVE) [PP] INTO CAPLIIARY HEAD 
!    (M)
     PSIC=-PP/GVA/RHOW0
!    CHECKING THE SOIL CHARACTERISTIC PARAMETERS
     IF(KREG.EQ.3)THEN
       DLAM=DLAM3
       PSICB=PSICB3
     ELSEIF(KERG.EQ.4)THEN
       DLAM=DLAM4   
       PSICB=PSICB4   
     ENDIF
!    EVALUATING RS BY DIFFERENT PSIC VALUE
     IF (PSIC.LE.PSICB)THEN
       SURFRSIS=0.D0
     ELSEIF (PSIC.GT.PSICB)THEN
!      KVRV INDUCED BY VAPOR AT STAGE IV SEE PAGE 229
       ETI=COER*0.66D0*TAL*POR*DLOG(PSIC0)/(YY*DLOG(PSIC+PSIP))
       ETRMS=1.D0-ETI
!      (E)FFECTIVE (S)ATURATION AFTER G FUNCTION
       SET=(PSICB/PSIC)**(DLAM*(1+EC))
!      POR*SET
       PORSE=POR*SET
!      PARAMETER IN THE HYPERGEOMETRIC
       C=(1/PORSE-1/SQRT(PORSE))/2.D0/TAL
!      EXPECTANT VALUE OF R1 AT GIVEN MATRIC POTENTIAL 
!      (UNDER BROOKS&COREY)
!      SEE EQUATION (A1) OF PAPER 2
       R1EFF=-DLAM*ZETA/(DLAM+1)/PSIC
       RELKV=1/(1+C*R1EFF)*ETRMS+ETI
       SURFRSIS=TAL/DVA(TSK)/RELKV
     ENDIF !PSIC
!  SEE PAGE 230, THE RESISTANCE INDUCED BY VAPOR BECOMES NON-TRIVAL WHEN THE 
!  NSL IS THIN.
   ELSEIF(MSR.EQ.9)THEN
!  THIS METHOD IS ENDORSED AS IT REPRESENTS PAPER2
!  CHECKED IN 2015-04-14 WITH PAPER2
!  CONVERT PORE WATER PRESSURE (NEGATIVE) [PP] INTO CAPLIIARY HEAD 
!    (M)
     PSIC=-PP/GVA/RHOW0
!    CHECKING THE SOIL CHARACTERISTIC PARAMETERS
     IF(KREG.EQ.3)THEN
       DLAM = DLAM3
       PSICB= PSICB3
     ELSEIF(KERG.EQ.4)THEN
       DLAM = DLAM4   
       PSICB= PSICB4   
     ENDIF
!    EVALUATING RS BY DIFFERENT PSIC VALUE
     IF (PSIC.LE.PSICB)THEN
       SURFRSIS=0.D0
     ELSEIF (PSIC.GT.PSICB)THEN
!      KVRV INDUCED BY VAPOR AT STAGE IV SEE PAGE 229,231
!      ETI IS EQUATION 20 IN PAPER2
       ETI=COER*0.66D0*TAL*POR*DLOG(PSIC0)/(YY*DLOG(PSIC+PSIP))
       ETRMS=1.D0-ETI
!      (E)FFECTIVE (S)ATURATION AFTER G FUNCTION
       SET=(PSICB/PSIC)**(DLAM*(1+EC))
!      POR*SET
       PORSE=POR*SET
!      PARAMETER IN THE HYPERGEOMETRIC
       C=(1/PORSE-1/SQRT(PORSE))/2.D0/TAL
!      EXPECTANT VALUE OF R1 AT GIVEN MATRIC POTENTIAL 
!      (UNDER BROOKS&COREY)
!      SEE EQUATION (A1) OF PAPER 2
       R1EFF=-DLAM*ZETA/(DLAM+1)/PSIC
       RELKV=1/(1+C*R1EFF)*ETRMS+ETI
       SURFRSIS=TAL/DVA(TSK)/RELKV
     ENDIF !PSIC
   ELSEIF(MSR.EQ.10)THEN
!      MSR = 10, SIMPLIFIED SR MODEL USING VAN GENUCHTEN WATER RETENTION CURVE
!      THE PROGRAMING IS STRICKLY ACCORDING TO THE ASSIGNMENT OF PAPER 2
!      PSIM (M) MATRIC POTENTIAL, ALWAY NEGATIVE HERE
!      TO 2015-04-15
!      SEE PAGE 2015-04-17 OF EIJKELKAMP BOOK
!      3 DAYS ARE SPENT TO TEST THIS FUNCTION, INCLUDING:
!      1  -- DERIVATION FROM EIJKELKAMP BOOK 2015-4-17 22-04-2015
!      2  -- DERIVATION FROM PAPER2
!      3  -- SAME PROGRAM IS WRITTEN IN FUN.KVR_C_S_VN in matlab
!      4  -- DIGGING ON F2PY, A FUNCTION TO MAKE FORTRAN SUBROUTINE INTO
!            PYTHON MODULES. IT IS NOT MATURE SO FAR
!      THE FINDING IS THAT:
!      1  -- THE FOLLOWING SUBROUTINE IS VERIFIED
!      2  -- THE EC=0.5 FOUND IN PAPER 2 SEEMS TO BE TOO SMALL FOR VAN 
!              GENUCHTEN MODEL
       PSIM=PP/GVA/RHOW0
       PSIC=-PSIM
       IF(KREG.EQ.1)THEN         
        SWRES=  SWRES1
        AA   =  -AA1
        VN   =  VN1
       ELSEIF(KREG.EQ.2)THEN     
        SWRES=  SWRES2
        AA   =  -AA2
        VN   =  VN2
       ENDIF !KREG
       ! PSICB IS ALWAYS A NEGATIVE VALUE
       BAPVN =  (AA*PSIM)**(VN-1.D0)
       AAPVN =  1.D0+BAPVN*AA*PSIM
       VNF   =  (VN-1.D0)/VN
       AAPVNN=  AAPVN**VNF
!      EFFECTIVE PORE SIZE EQUATION (A4) IN PAPER2     
       R1EFF   =  ZETA*AA*(AAPVNN-BAPVN)
!      CLEARLY IT IS FOUND THAT THE LAMBDA IN BK AND VN IN VAN IS NOT THE 
!      SAME. HOWEVER, WE ASSUME IT IS EQUIVALENT HERE (HAVEN'T TESTED YET)
!      KVRV INDUCED BY VAPOR AT STAGE IV SEE PAGE 229,231
!      ETI IS EQUATION 20 IN PAPER2
       ETI=COER*0.66D0*TAL*POR*DLOG(PSIC0)/(YY*DLOG(PSIC+PSIP))
       ETRMS=1.D0-ETI
!      (E)FFECTIVE (S)ATURATION AFTER G FUNCTION
!       SET=(PSICB/PSIM)**(VN*(1.D0+EC))
       SLENSL=AAPVN**(-VNF)
       SET = SLENSL**(1.D0+EC)
!      POR*SET
       PORSE=POR*SET
!      PARAMETER IN THE HYPERGEOMETRIC
       C=(1.D0/PORSE-1.D0/SQRT(PORSE))/2.D0/TAL
!      EXPECTANT VALUE OF R1 AT GIVEN MATRIC POTENTIAL 
!      (UNDER BROOKS&COREY)
!      SEE EQUATION (A1) OF PAPER 2
       RELKV=1.D0/(1.D0+C*R1EFF)*ETRMS+ETI
       SURFRSIS=TAL/DVA(TSK)/RELKV
   ENDIF ! MSR
   IF (SURFRSIS.LT.0.D0) SURFRSIS=0.D0
   RETURN 
   END FUNCTION SURFRSIS

