




DOUBLE PRECISION FUNCTION TAO (POR,SW)
IMPLICIT NONE
DOUBLE PRECISION :: POR,SW
  TAO=POR**(1.D0/3.D0)*(1-SW)**(7.D0/3.D0)
RETURN 
END FUNCTION TAO


DOUBLE PRECISION FUNCTION THEA (POR,SW)
IMPLICIT DOUBLE PRECISION (A-H,O-Z)
THEA=POR*(1-SW)
RETURN 
END FUNCTION THEA


! WHEN N=1, IT CALCULATES SATURATED VAPOR PRESSURE
! WHEN N=2, IT CALCULATES THE DERIVATIVE OF SATURATED VAPOR PRESSURE 
! TO T 
DOUBLE PRECISION FUNCTION PSAT(N,TK)
  IMPLICIT DOUBLE PRECISION (A-H, O-Z) 
    IF (N.EQ.1) THEN
!     SATURATED VAPOR PRESSURE AT TEMP TK
      PSAT=6.11D2*EXP(17.27*(TK-273.15)/(TK-35.85))   
    ELSEIF (N.EQ.2)THEN
!    DELTA P  = DP/DT  
     PSAT=2.504D6/(TK-35.85D0)**2.D0*    &
      EXP(17.27D0*(TK-273.15D0)/(TK-35.85D0))     
    ENDIF
  RETURN
END FUNCTION PSAT



!       DIFFUSION OF WATER VAPOR IN THE AIR
DOUBLE PRECISION FUNCTION DVA (TK)
  IMPLICIT DOUBLE PRECISION (A-H,O-Z)
  DVA=2.29D-5*(TK/273.15D0)**1.75D0
  RETURN
END FUNCTION DVA

DOUBLE PRECISION FUNCTION RHOWVSAT (N,TK)
  IMPLICIT DOUBLE PRECISION (A-H,O-Z)
  IF (N.EQ.1) THEN
   RHOWVSAT = 1D-3*EXP(19.819-4976/TK)
  ELSEIF (N.EQ.2) THEN
   RHOWVSAT = 4.976D0*EXP(19.819D0-4976D0/TK)/TK**2.D0
  ENDIF
  RETURN
END FUNCTION RHOWVSAT






!  FUNCTION FYM IS TO CALCULATE THE OSMOTICAL POTENTIAL FROM PORE WATE
!  R PRESSURE
!     INPUT CONDITIONS 
!      P -- PORE WATER PRESSURE [PA]
!     ROU - PURE WATER DENSITY [KG/M3]
!     G  -- GRAVATIONAL ACCERATION [M/S2]
DOUBLE PRECISION FUNCTION FYM(P)
  IMPLICIT DOUBLE PRECISION (A-H,O-Z)
  DATA  ROU/1.D3/, G/9.8D0/
  SAVE ROU,G
  FYM=P/ROU/G
  RETURN 
END FUNCTION FYM



!      FUNCTION FYO IS TO CALCULATE THE OSMOTICAL POTENTIAL FROM PORE
!      WATER PRESSURE
!     CALLED FUNCTION AND SUBROUTINES:
!     CHI(C) TO GET OSMOTIC COEFFICIENTS, BASED ON ROBINSON AND 
!     STOKES (1965)
DOUBLE PRECISION FUNCTION FYO(C,T)
  IMPLICIT DOUBLE PRECISION (A-H,O-Z)
  DATA  RC/8.314472D+0/,G/9.8D0/,STM/5.85D-2/
  SAVE RC,G,STM
  FYO=-2.D0*CHI(C)*C*RC*T/G/STM
  RETURN 
END FUNCTION FYO


!     FUNCTION HR IS TO CALCULATE THE RELATIVE HUMIDITY ACCORDING TO 
!     KELVEN'S EQUATION
DOUBLE PRECISION FUNCTION HR(FM,FO,T)
IMPLICIT DOUBLE PRECISION (A-H,O-Z)
DATA  RC/8.314472D+0/,G/9.8D0/,WMW/1.8D-2/
SAVE RC,G,WMW
HR=EXP((FM+FO)*G*WMW/RC/T)
RETURN 
END FUNCTION HR



SUBROUTINE AEROSIST(RAVT,MAR)
IMPLICIT DOUBLE PRECISION (A-H,O-Z)
RETURN
END SUBROUTINE AEROSIST

DOUBLE PRECISION FUNCTION CHI (C)
IMPLICIT DOUBLE PRECISION (A-H,O-Z)
! EMPIRICAL EQUATION
CHI=.9D0+2.6D-3*(C/(1-C))*1.D3+2.6D-3*((C/(1-C))*1.D3)**5.3D-2
RETURN
END FUNCTION CHI
