SUBROUTINE INDATET ()
! THIS USE HAS SPEND 1 DAY ON DEBUGGING THIS. SPECIFICALLY, IF INBUILDING
! FUNCTION READIF IS CALLED, 'USE EXPINT' HAS TO BE CALLED, WHICH INCLUDES
! AN INTERFACE FOR READIF.
! IF USE F90, ONE MAY NOT SEE ERROR WHILE COMPILING
! IF USE F77, ONE SEE ERROR 
!
! Error: Dummy argument 'cherin' of procedure 'readif' at 
! (1) has an attribute that requires an explicit interface for this
! procedure
!
! ON GDB
  USE EXPINT
  USE M_ET
  USE M_CTRL
  USE M_SWCC
  USE M_AEROR
  USE M_SURFR
  USE M_SALTR
  USE M_TIDE
  USE M_FILM
  IMPLICIT NONE 
  INTEGER(4) :: K1
  CHARACTER*80 :: ERRCOD
  CHARACTER INTFIL*1000 
  K1 = 1
  OPEN(UNIT=K1,FILE='ET.INP',STATUS='OLD')           
  ERRCOD = 'CTRL'      
  CALL READIF(K1, 0, INTFIL, ERRCOD)                                
  READ(INTFIL,*) MET,MAR,MSR,MSC,MHT,MVT,MFT,MRK
!   DATASET 13D: EVAPORATION SINARIO
!     QET... (MM/DAY) NON OF USE SO FAR
!     UET... (KG/KG) THE SOLUTE DENSITY OF WATER TAKEN BY EVAPORATION
!     PET... (PA) WHEN PORE WATER PRESSURE REACHED THE POINT LOWER THAN 
!            PET, EVAPORATION IS TAKING PLACE
!     UVM... (KG/KG) SOLUBILITY
!     NGT... IF =1 EVAPORATION IS SWICHED OFF DURING NIGHT TIME, IF =0
!            IT IS ALWAYS ON
!     ITE... TEMPERATORYLY NOT USING, IT WAS
!             DESIGNED FOR THE NUMBER OF TIME CALL FOR BCTIME
!     PRDDN ...  PERIOD OF DAY AND NIGHT IF IT IS ZERO, THEN EVAPORATION IS CONSTANT
!     OFSTDN...  OFFSET OF THE EVAPORATION DURING THE DAY AND NIGHT
!      IF (MET.NE.0)THEN
  ERRCOD = 'TIDE'      
  CALL READIF(K1, 0, INTFIL, ERRCOD)                                
  READ(INTFIL,*) TASP,TANE,TPSP,TPNP,TM,RHOST,SC
  ERRCOD = 'ET'      
  CALL READIF(K1, 0, INTFIL, ERRCOD)                                
  READ(INTFIL,*) QET,UET,PET,UVM,PRDDN,OFSTDN 
  ERRCOD = 'ET2'      
  CALL READIF(K1, 0, INTFIL, ERRCOD)                                
  READ(INTFIL,*) TMA,TMI,ALF,RS,RH,AP,BP,U2,TSD,SCF
  ERRCOD = 'SWCC'
  CALL READIF(K1, 0, INTFIL, ERRCOD)                                
  READ(INTFIL,*) SWRES1,AA1,VN1,SWRES2,AA2,VN2,SWRES3,DLAM3,PSICB3, &
      SWRES4,DLAM4,PSICB4,PSIC0,ECTO
  ERRCOD = 'AEROSIS'
  CALL READIF(K1, 0, INTFIL, ERRCOD)                                
  READ(INTFIL,*) RAVT,RAVS,SWRAT
  ERRCOD = 'SURFRSIS'
  CALL READIF(K1, 0, INTFIL, ERRCOD)                                
  READ(INTFIL,*) TAL,EC,ETR,PSIP,COER
  ERRCOD = 'SALTRSIS'
  CALL READIF(K1, 0, INTFIL, ERRCOD)                                
  READ(INTFIL,*) AR,BR
  ERRCOD = 'FILM'
  CALL READIF(K1, 0, INTFIL, ERRCOD)                                
  READ(INTFIL,*) CORF,AGR,SWM,ASVL
  CLOSE(K1)
  RETURN
END SUBROUTINE INDATET 





!SUBROUTINE INDATTIDE ()
!  USE EXPINT
!  IMPLICIT NONE 
!  INTEGER(4) :: K1
!  CHARACTER*80 :: ERRCOD
!  CHARACTER INTFIL*1000 
!  K1 = 1
!  OPEN(K1,FILE='TIDE.INP',STATUS='OLD',FORM='FORMATTED')           
!  ERRCOD = 'TIDE'      
!  CALL READIF(K1, 0, INTFIL, ERRCOD)                                
!  READ(INTFIL,*) TASP,TANE,TPSP,TPNP,TM,RHOST,SC
!  CLOSE(K1)
!  RETURN
!END SUBROUTINE INDATTIDE 
!                        TEMP. (TM) [PA]
!     FU   -- WIND FUNCTION [MJ/M2/KPA/DAY]
!     AP,BP-- PARAMETER IN WIND FUNCTION
!     U2   -- DAILY MEAN WIND SPEED AT 2M ABOVE GROUND [KM/DAY]
!     RC   -- UNIVERSAL GAS CONSTANT [J/MOL/K]
!     WMW   -- MOLECULAR WEIGHT OF WATER [KG/MOL]
!     TS   -- SOIL TEMPERATURE [CELSIUS]
!     DP   -- VAN'T HOFF DISSOCIATION FACTOR
!     STM  -- MOLECULAR WEIGHT OF NACL [KG/MOL]
!     FIO(NOT ZERO)  -- OSMOTIC POTENTIALS (M)
!     HO(NOT ZERO)   -- OSMOTIC PARAMETER
!     RHOW0   -- INITIAL WATER DENSITY (KG/M3)
!      TSK   -- TEMPERATURE AT THAT NODE
!      TMAK   -- TEMPERATURE AT THAT NODE  
! ... PEMAN METHOD ...      
!      IF (MET.EQ.1) THEN ! USING PENMAN EVAPORATION EQUATION
!      TMAK=273.15D0+TMA                                   
!      ! AIR TEMPERATURE TMAK=(TMA-273.15D0)
!!     LATENT HEAT FOR VAPORIZATION   [J/KG]
!      VLH=(2.50025-0.002365*(TMAK-273.15D0))*1.D6   
!! CAPITAL GAMA FOR CALCULATING DEW POINT TEMP.
!      CGA=17.271*(TMAK-273.15D0)/(237.7+(TMAK-273.15D0))+LOG(RH)      
!    ! DEW POINT [K]
!      TD=237.7*CGA/(17.271-CGA)+273.15                            
!      RMG=0.D0                            
!      HO=EXP(-WMW*2.D0*CHI(CC)*CC/STM)
!      HM=EXP(WMW*PC/RHOW0/RC/TSK)
!      DFR=RSC                                          ! OUTPUT 
!      PWFR=HO                                          ! OUTPUT
!      PCFR=HM                                          ! OUTPUT
!
!
!      PA=1.01D5    ! ATMOSPHEREIC PRESSURE                 [PA]
!      DMOA=0.02897       ! MOLECULAR WEIGHT OF AIR (KG/MOL)       
!
!      RHOA=PA*DMOA/RC/TMAK
!      GAMA=66.D0                      ! PSYCHOMETRIC CONSTANT  [PA/K]
!      DLNUM=HO*HM*PSAT(2,TMAK)*RMG
!      DRNUM=CA*RHOA/RAVT*(HO*HM*PSAT(1,TMAK)-PSAT(1,TD))
!      DENO=VLH*RHOW0*(HO*HM*PSAT(2,TMAK)+GAMA*(RAVT+RSC)/RAVT)
!      AET=-(DLNUM+DRNUM)/DENO
!      ELSEIF (MET.EQ.2) THEN                         
!! AIR TEMPERATURE TMAK=(TMA-273.15D0)
!      TMAK=273.15D0+TMA     
!      TERM1=WMW/RHOW0/RC
!! RELATIVE HUMIDITY INDUCED BY OSMOTICAL POTENTIAL 
!      HO=EXP(-WMW*2.D0*CHI(CC)*CC/STM)      
!! RELATIVE HUMIDITY INDUCED BY MATRIC POTENTIAL
!      HM=EXP(WMW*PC/RHOW0/RC/TSK)         
!! DFR, PWFR AND PCFR IS USED FOR OUTPUT IN .BCOF
!      DFR=RSC                                       
!      PWFR=HO
!      PCFR=HM
!      SURF=SURFRSIS(PC,POR,SW,MSR,KREG,TSK,YY)
!      AET=-TERM1*(PSAT(1,TSK)*HO*HM/TSK-PSAT(1,TMAK)*RH/TMAK)/  &
!          (RAVT+SURF+RSC)
!      WRITE (48,"( 7(1PE15.7))") SURF,SW,PC,TSK,HO,HM,AET
!! SOME COMMENTS ON FORMAT IN FORTRAN 90 
!! 7(1PE15.7) HERE 7 MEANS OUTPUT 7 TIMES
!!                1P MEANS THE FIRST VALUE IS NON-ZERO 
!!                   E.G., 1.3D1 NOT 0.13D2
!!              EW.D EXPONENTIAL, TOTAL WIDTH, AND DECIMAL WIDTH
!!                   IT IS ALSO ACCEPTABLE TO USE NUMBER TO REFERENCE THE
!!                      FORMAT STYLE  
!!1 FORMAT( 7(1PE20.7))
!       ENDIF
!      RETURN
!      END SUBROUTINE EVAPORATION
